Lighten_Project/Models/Blogs.cs
using System.ComponentModel.DataAnnotations;

namespace Lighten_Project.Models
{
    public class Blogs
    {
        [Key]
        public int Id { get; set; }
        
        public string Picture { get; set; }

       
        [MaxLength(50, ErrorMessage = "Simvol sayi 50 simvoldan cox ola bilmez")]
        public string Title { get; set; }
       
        public string Date { get; set; }
        
        [MaxLength(400, ErrorMessage = "Simvol sayi 400-den cox ola bilmez")]
        public string UpTitle { get; set; }
    }
}

Lighten_Project/Models/OurProducts.cs
using System.ComponentModel.DataAnnotations;

namespace Lighten_Project.Models
{
    public class OurProducts
    {
        [Key]
        public int Id { get; set; }
       
        public string Picture { get; set; }

        
        [MaxLength(60, ErrorMessage = "Simvol sayi 60-den cox ola bilmez")]
        public string Title { get; set; }

        
        public string Price  { get; set; }

    }
}

Lighten_Project/Models/ServiceProses.cs
using Lighten_Project.Models;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;

namespace Lighten_Project.Models
{
    public class ServiceProses
    {
        [Key]
        public int Id { get; set; }
        
        public string Icon { get; set; }

       
        [MaxLength(50, ErrorMessage = "Simvol sayi 50-den cox ola bilmez")]
        public string Title { get; set; }

        
        [MaxLength(400, ErrorMessage = "Simvol sayi 400-den cox ola bilmez")]
        public string UpTitle { get; set; }

    }
}

Lighten_Project/Models/WhyChooseUs.cs
using Lighten_Project.Models;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;

namespace Lighten_Project.Models
{
    public class WhyChooseUs
    {
        [Key]
        public int Id { get; set; }

       
        public string Picture { get; set; }

        [MaxLength(50,ErrorMessage ="Simvol sayi 50-den cox ola bilmez")]
        public string Title { get; set; }
        
        
        [MaxLength(400, ErrorMessage = "Simvol sayi 400-den cox ola bilmez")]
        public string UpTitle { get; set; }

    }
}

Lighten_Project/Controllers/AboutController.cs
using Lighten_Project.Models;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;

namespace Lighten_Project.Controllers
{
    public class AboutController : Controller
    {
        private readonly Data.Lighten_ProjectDbContext context1;

        public AboutController(Data.Lighten_ProjectDbContext context)
        {
            context1 = context;
            
        }
       
        public IActionResult Index()
        {

            List<WhyChooseUs> us = context1.WhyChooseUs.ToList();
            return View(us);
        }


       


    }
}    
  



   

Lighten_Project/Controllers/BlogController.cs
using Lighten_Project.Data;
using Lighten_Project.Models;
using Microsoft.AspNetCore.Mvc;

namespace Lighten_Project.Controllers
{
    
    public class BlogController : Controller
    {
        private readonly Data.Lighten_ProjectDbContext _context;
        public BlogController(Data.Lighten_ProjectDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            List<Blogs> blogs=_context.Blogs.ToList();
            return View(blogs);
        }
    }
}

Lighten_Project/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;

namespace Lighten_Project.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Lighten_Project/Controllers/HomeController.cs
using Lighten_Project.Models;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;

namespace Lighten_Project.Controllers
{
    public class HomeController : Controller
    {
        private readonly Data.Lighten_ProjectDbContext context2;

        public HomeController(Data.Lighten_ProjectDbContext context)
        {
            context2 = context;

        }

        public IActionResult Index()
        {

            List<ServiceProses> processes = context2.ServiceProses.ToList();
            return View(processes);
        }
    }


}

Lighten_Project/Controllers/ProductController.cs
using Lighten_Project.Models;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;

namespace Lighten_Project.Controllers
{
    public class ProductController : Controller
    {
        private readonly Data.Lighten_ProjectDbContext context3;
        public ProductController(Data.Lighten_ProjectDbContext context)
        {
            context3 = context;
        }
        public IActionResult Index()
        {
            List<OurProducts> products = context3.OurProducts.ToList();
            return View(products);
            
        }
    }
}

Lighten_Project/Views/About/Index.cshtml
@model List<WhyChooseUs>

 List<ServiceProses>

<div class="brand_color">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="titlepage">
                    <h2>about</h2>
                </div>
            </div>
        </div>
    </div>

</div>


<div class="about">
    <div class="container">
        <div class="row">
            <dir class="col-xl-6 col-lg-6 col-md-12 col-sm-12">
                <div class="about_box">
                    <figure><img src="images/pc_layout.png" /></figure>
                </div>
            </dir>
            <dir class="col-xl-6 col-lg-6 col-md-12 col-sm-12">
                <div class="about_box">
                    <h3>Who is Lighten</h3>
                    <p>It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum.</p>
                    <p>Simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
                </div>
            </dir>
        </div>
    </div>
</div>

<!-- CHOOSE  -->
<div class="whyschose">
    <div class="container">

        <div class="row">
            <div class="col-md-7 offset-md-3">
                <div class="title">
                    <h2>Why <strong class="black">choose us</strong></h2>
                    <span>Fastest repair service with best price!</span>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="choose_bg">
    <div class="container">
        <div class="white_bg">
            <div class="row">


                
                @foreach (var informationUs in Model)
                {
                    <div class="col-xl-3 col-lg-3 col-md-6 col-sm-12">
                        <div class="for_box">
                            <i><img src="icon/@informationUs.Picture" /></i>
                            <h3>@informationUs.Title</h3>
                            <p>@informationUs.UpTitle</p>
                        </div>
                    </div>
                }
                
               


                <div class="col-md-12">
                    <a class="read-more">Read More</a>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- end CHOOSE -->
<!-- service -->
<div class="service">
    <div class="container">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                <div class="title">
                    <h2>service <strong class="black">proces</strong></h2>
                    <span>Easy and effective way to get your device repaired.</span>
                </div>
            </div>
        </div>
        <div class="row">

          
            <div class="col-xl-4 col-lg-4 col-md-4 col-sm-12">
                <div class="service-box">
                    <i><img src="icon/service1.png" /></i>
                    <h3>Fast service</h3>
                    <p>Exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea </p>
                </div>
            </div>
            <div class="col-xl-4 col-lg-4 col-md-4 col-sm-12">
                <div class="service-box">
                    <i><img src="icon/service2.png" /></i>
                    <h3>Secure payments</h3>
                    <p>Exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea </p>
                </div>
            </div>
            <div class="col-xl-4 col-lg-4 col-md-4 col-sm-12">
                <div class="service-box">
                    <i><img src="icon/service3.png" /></i>
                    <h3>Expert team</h3>
                    <p>Exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea </p>
                </div>
            </div>
            <div class="col-xl-4 col-lg-4 col-md-4 col-sm-12">
                <div class="service-box">
                    <i><img src="icon/service4.png" /></i>
                    <h3>Affordable services</h3>
                    <p>Exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea </p>
                </div>
            </div>
            <div class="col-xl-4 col-lg-4 col-md-4 col-sm-12">
                <div class="service-box">
                    <i><img src="icon/service5.png" /></i>
                    <h3>90 Days warranty</h3>
                    <p>Exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea </p>
                </div>
            </div>
            <div class="col-xl-4 col-lg-4 col-md-4 col-sm-12">
                <div class="service-box">
                    <i><img src="icon/service6.png" /></i>
                    <h3>Award winning</h3>
                    <p>Exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea </p>
                </div>
            </div>


        </div>
    </div>
</div>
<!-- end service -->

Lighten_Project/Views/Blog/Index.cshtml
@model List<Blogs>;

<div class="brand_color">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="titlepage">
                    <h2>blog</h2>
                </div>
            </div>
        </div>
    </div>

</div>
<!-- Lastestnews -->
<div class="Lastestnews blog">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="titlepage">

                    <span>It is a long established fact that a reader will be distracted by the readable <br>content of a page when looking at its layout. The point of using Lorem </span>
                </div>
            </div>
        </div>
        <div class="row">
            @foreach(var blogs in Model)
            {
                <div class="col-xl-4 col-lg-4 col-md-4 col-sm-12 margin">
                    <div class="news-box">
                        <figure><img src="images/@blogs.Picture" alt="img" /></figure>
                        <h3>@blogs.Title</h3>
                        <span>@blogs.Date</span>
                        <p>@blogs.UpTitle</p>
                    </div>
                </div>
            }
           
            
        </div>
    </div>
</div>
<!-- end Lastestnews -->

Lighten_Project/Views/Contact/Index.cshtml
<div class="brand_color">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="titlepage">
                    <h2>Contact Us</h2>
                </div>
            </div>
        </div>
    </div>

</div>

<!-- contact -->
<div class="contact">
    <div class="container">
        <div class="row">
            <div class="col-md-12">

                <form class="main_form">
                    <div class="row">
                        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6">
                            <input class="form-control" placeholder="Your name" type="text" name="Your Name">
                        </div>
                        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6">
                            <input class="form-control" placeholder="Email" type="text" name="Email">
                        </div>

                        <div class=" col-md-12">
                            <input class="form-control" placeholder="Phone" type="text" name="Phone">
                        </div>
                        <div class="col-md-12">
                            <textarea class="textarea" placeholder="Message"></textarea>
                        </div>
                        <div class=" col-md-12">
                            <button class="send">Send</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- end contact -->

Lighten_Project/Views/Product/Index.cshtml
@model List<OurProducts>

<div class="brand_color">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="titlepage">
                    <h2>our product</h2>
                </div>
            </div>
        </div>
    </div>

</div>
<!-- our product -->
<div class="product">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="title">

                    <span>We package the products with best services to make you a happy customer.</span>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="product-bg">
    <div class="product-bg-white">
        <div class="container">
            <div class="row">
                @foreach (var products in Model)
                {
                    <div class="col-xl-3 col-lg-3 col-md-6 col-sm-12">
                        <div class="product-box">
                            <i><img src="icon/@products.Picture" /></i>
                            <h3>@products.Title</h3>
                            <span>@products.Price</span>
                        </div>
                    </div>

                }
               

            </div>
        </div>
    </div>
</div>

Lighten_Project/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- basic -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- mobile metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
    <!-- site metas -->
    <title>lighten</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- bootstrap css -->
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <!-- style css -->
    <link rel="stylesheet" href="css/style.css">
    <!-- Responsive-->
    <link rel="stylesheet" href="css/responsive.css">
    <!-- fevicon -->
    <link rel="icon" href="images/fevicon.png" type="image/gif" />
    <!-- Scrollbar Custom CSS -->
    <link rel="stylesheet" href="css/jquery.mCustomScrollbar.min.css">
    <!-- Tweaks for older IEs-->
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" media="screen">
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
</head>
<!-- body -->
<body class="main-layout">
    <!-- loader  -->
    <div class="loader_bg">
        <div class="loader"><img src="images/loading.gif" alt="#" /></div>
    </div>
    <!-- end loader -->
    <!-- header -->
    <header>
        <!-- header inner -->
        <div class="header">
            <div class="head_top">
                <div class="container">
                    <div class="row">
                        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12">
                            <div class="top-box">
                                <ul class="sociel_link">
                                    <li> <a href="#"><i class="fa fa-facebook-f"></i></a></li>
                                    <li> <a href="#"><i class="fa fa-twitter"></i></a></li>
                                    <li> <a href="#"><i class="fa fa-instagram"></i></a></li>
                                    <li> <a href="#"><i class="fa fa-linkedin"></i></a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12">
                            <div class="top-box">
                                <p>long established fact that a reader will be </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="row">
                    <div class="col-xl-3 col-lg-3 col-md-3 col-sm-3 col logo_section">
                        <div class="full">
                            <div class="center-desk">
                                <div class="logo"> <a href="index.html"><img src="images/logo.jpg" alt="logo" /></a> </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-7 col-lg-7 col-md-9 col-sm-9">
                        <div class="menu-area">
                            <div class="limit-box">
                                <nav class="main-menu">
                                    <ul class="menu-area-main">
                                        <li class="active"> <a asp-controller="Home" action="Index">Home</a> </li>
                                        <li> <a asp-controller="About" asp-action="Index">About</a> </li>
                                        <li> <a asp-controller="Product" asp-action="Index">product</a> </li>
                                        <li> <a asp-controller="Blog" asp-action="Index"> Blog</a> </li>
                                        <li> <a asp-controller="Contact" asp-action="Index">Contact</a> </li>
                                        <li class="mean-last"> <a href="#contact">signup</a> </li>

                                    </ul>
                                </nav>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-2 col-lg-2 col-md-2 col-sm-2">
                        <ul>
                        <li><a class="buy" href="#">Login</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- end header inner -->
            </div>
    </header>
    <!-- end header -->
    @RenderBody();
    <!--  footer -->




    <footr>
        <div class="footer">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 offset-md-3">
                        <ul class="sociel">
                            <li> <a href="#"><i class="fa fa-facebook-f"></i></a></li>
                            <li> <a href="#"><i class="fa fa-twitter"></i></a></li>
                            <li> <a href="#"><i class="fa fa-instagram"></i></a></li>
                            <li> <a href="#"><i class="fa fa-instagram"></i></a></li>
                        </ul>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xl-3 col-lg-3 col-md-6 col-sm-12">
                        <div class="contact">
                            <h3>conatct us</h3>
                            <span>
                                123 Second Street Fifth Avenue,<br>
                                Manhattan, New York<br>
                                +987 654 3210
                            </span>
                        </div>
                    </div>
                    <div class="col-xl-3 col-lg-3 col-md-6 col-sm-12">
                        <div class="contact">
                            <h3>ADDITIONAL LINKS</h3>
                            <ul class="lik">
                                <li> <a href="#">About us</a></li>
                                <li> <a href="#">Terms and conditions</a></li>
                                <li> <a href="#">Privacy policy</a></li>
                                <li> <a href="#">News</a></li>
                                <li> <a href="#">Contact us</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-xl-3 col-lg-3 col-md-6 col-sm-12">
                        <div class="contact">
                            <h3>service</h3>
                            <ul class="lik">
                                <li> <a href="#"> Data recovery</a></li>
                                <li> <a href="#">Computer repair</a></li>
                                <li> <a href="#">Mobile service</a></li>
                                <li> <a href="#">Network solutions</a></li>
                                <li> <a href="#">Technical support</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-xl-3 col-lg-3 col-md-6 col-sm-12">
                        <div class="contact">
                            <h3>About lighten</h3>
                            <span>Tincidunt elit magnis nulla facilisis. Dolor Sapien nunc amet ultrices, </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="copyright">
                <p>Copyright 2019 All Right Reserved By <a href="https://html.design/">Free html Templates</a> Distributed By <a href="https://themewagon.com">ThemeWagon </a></p>
            </div>

        </div>
    </footr>
    <!-- end footer -->
    <!-- Javascript files-->
    <script src="js/jquery.min.js"></script>
    <script src="js/popper.min.js"></script>
    <script src="js/bootstrap.bundle.min.js"></script>
    <script src="js/jquery-3.0.0.min.js"></script>
    <script src="js/plugin.js"></script>
    <!-- sidebar -->
    <script src="js/jquery.mCustomScrollbar.concat.min.js"></script>
    <script src="js/custom.js"></script>
    <script src="https:cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js"></script>
    <script>
        $(document).ready(function () {
            $(".fancybox").fancybox({
                openEffect: "none",
                closeEffect: "none"
            });

            $(".zoom").hover(function () {

                $(this).addClass('transition');
            }, function () {

                $(this).removeClass('transition');
            });
        });

    </script>
</body>
</html>